blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/oimiragieo/reveng-main/tree/main/docs
    about: Check our comprehensive documentation for answers
  - name: 💬 Discussions
    url: https://github.com/oimiragieo/reveng-main/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/oimiragieo/reveng-main/security/advisories/new
    about: Report security vulnerabilities privately
