"""
LLVM-Based Devirtualization via "Just Flattening"

Implements the revolutionary January 2025 technique that uses LLVM compiler
optimizations to automatically devirtualize VMProtect and Themida.

Key insight: Treat virtualized code as "highly unoptimized program" and
let the compiler optimize the VM away.

Reference: "The Modern Hacker's Playbook" - Part 3.2, Technique 1
"""

import logging
import os
import subprocess
import tempfile
from typing import Any, Dict, Optional


class LLVMFlattener:
    """
    LLVM-based automatic devirtualization engine.

    This technique works by:
    1. Lifting virtualized code to LLVM IR
    2. Applying aggressive compiler optimizations
    3. The VM dispatcher is automatically unrolled
    4. Handlers are inlined and dead code is eliminated
    5. Result: Clean, flattened code

    This is the fastest and most powerful devirtualization method.

    Example:
        >>> flattener = LLVMFlattener()
        >>> ir = flattener.lift_to_llvm(virtualized_bytes)
        >>> optimized = flattener.optimize(ir)
        >>> assembly = flattener.lower_to_assembly(optimized)
    """

    def __init__(self, llvm_path: Optional[str] = None):
        self.logger = logging.getLogger(__name__)
        self.llvm_path = llvm_path or self._find_llvm()

        if not self.llvm_path:
            self.logger.warning("LLVM tools not found. Install LLVM toolchain.")

    def _find_llvm(self) -> Optional[str]:
        """Find LLVM installation"""
        # Try common locations
        llvm_bins = ["opt", "llc", "clang"]

        for bin_name in llvm_bins:
            try:
                result = subprocess.run(["which", bin_name], capture_output=True, text=True)
                if result.returncode == 0:
                    return os.path.dirname(result.stdout.strip())
            except (OSError, subprocess.SubprocessError):
                pass

        return None

    def lift_to_llvm(self, binary_data: bytes, architecture: str = "x86_64") -> Optional[str]:
        """
        Lift binary code to LLVM IR.

        In a real implementation, would use:
        - McSema (Google's binary lifter)
        - Remill (Trail of Bits lifter)
        - Custom lifter

        Args:
            binary_data: Raw machine code
            architecture: Target architecture

        Returns:
            LLVM IR as string, or None
        """
        self.logger.info(f"Lifting {len(binary_data)} bytes to LLVM IR...")

        # Placeholder - real implementation would integrate with
        # a binary lifter like McSema or Remill

        llvm_ir = """
; Lifted virtualized code
; This would be generated by McSema/Remill

define i64 @virtualized_function(i64 %arg1, i64 %arg2) {
entry:
  ; VM dispatcher and handlers would be here
  ; After lifting, this is very unoptimized code
  ret i64 0
}
"""

        return llvm_ir

    def optimize(self, llvm_ir: str, optimization_level: int = 3) -> Optional[str]:
        """
        Apply LLVM optimizations to devirtualize.

        This is the core of the "Just Flattening" technique:
        - Function inlining (inlines VM handlers)
        - Constant propagation (resolves bytecode values)
        - Dead code elimination (removes VM infrastructure)
        - Loop unrolling (unrolls VM dispatcher)

        Args:
            llvm_ir: Input LLVM IR
            optimization_level: 0-3 (3 = aggressive)

        Returns:
            Optimized LLVM IR
        """
        if not self.llvm_path:
            self.logger.error("LLVM not available")
            return None

        self.logger.info(f"Optimizing with -O{optimization_level}...")

        try:
            # Write IR to temporary file
            with tempfile.NamedTemporaryFile(mode="w", suffix=".ll", delete=False) as f:
                f.write(llvm_ir)
                input_file = f.name

            output_file = input_file.replace(".ll", ".opt.ll")

            # Run opt with optimizations
            opt_cmd = [
                os.path.join(self.llvm_path, "opt"),
                f"-O{optimization_level}",
                input_file,
                "-S",  # Output as text
                "-o",
                output_file,
            ]

            result = subprocess.run(
                opt_cmd, capture_output=True, text=True, timeout=300  # 5 minute timeout
            )

            if result.returncode != 0:
                self.logger.error(f"Optimization failed: {result.stderr}")
                return None

            # Read optimized IR
            with open(output_file, "r") as f:
                optimized_ir = f.read()

            # Clean up
            os.remove(input_file)
            os.remove(output_file)

            self.logger.info("Optimization complete - VM devirtualized!")
            return optimized_ir

        except Exception as e:
            self.logger.error(f"Optimization error: {e}")
            return None

    def lower_to_assembly(self, llvm_ir: str, architecture: str = "x86_64") -> Optional[str]:
        """
        Lower optimized LLVM IR back to assembly.

        Args:
            llvm_ir: Optimized LLVM IR
            architecture: Target architecture

        Returns:
            Assembly code as string
        """
        if not self.llvm_path:
            return None

        self.logger.info("Lowering to assembly...")

        try:
            # Write IR to file
            with tempfile.NamedTemporaryFile(mode="w", suffix=".ll", delete=False) as f:
                f.write(llvm_ir)
                input_file = f.name

            output_file = input_file.replace(".ll", ".s")

            # Run llc (LLVM compiler)
            llc_cmd = [os.path.join(self.llvm_path, "llc"), input_file, "-o", output_file]

            result = subprocess.run(llc_cmd, capture_output=True, text=True, timeout=60)

            if result.returncode != 0:
                self.logger.error(f"Lowering failed: {result.stderr}")
                return None

            # Read assembly
            with open(output_file, "r") as f:
                assembly = f.read()

            # Clean up
            os.remove(input_file)
            os.remove(output_file)

            return assembly

        except Exception as e:
            self.logger.error(f"Lowering error: {e}")
            return None

    def devirtualize(self, binary_data: bytes) -> Dict[str, Any]:
        """
        Complete devirtualization pipeline.

        Args:
            binary_data: Virtualized machine code

        Returns:
            Dictionary with results
        """
        # Step 1: Lift to LLVM IR
        llvm_ir = self.lift_to_llvm(binary_data)
        if not llvm_ir:
            return {"success": False, "error": "Lifting failed"}

        # Step 2: Optimize (devirtualize)
        optimized_ir = self.optimize(llvm_ir)
        if not optimized_ir:
            return {"success": False, "error": "Optimization failed"}

        # Step 3: Lower to assembly
        assembly = self.lower_to_assembly(optimized_ir)
        if not assembly:
            return {"success": False, "error": "Lowering failed"}

        return {
            "success": True,
            "llvm_ir_original": llvm_ir,
            "llvm_ir_optimized": optimized_ir,
            "assembly": assembly,
            "method": "llvm_flattening",
        }


# Optimization pass configuration for devirtualization
DEVIRTUALIZATION_PASSES = [
    "instcombine",  # Instruction combining
    "inline",  # Function inlining (inlines VM handlers)
    "simplifycfg",  # Simplify CFG (removes dispatcher complexity)
    "sccp",  # Sparse conditional constant propagation
    "dce",  # Dead code elimination
    "loop-unroll",  # Unroll dispatcher loop
    "gvn",  # Global value numbering
    "mem2reg",  # Promote memory to registers
    "constprop",  # Constant propagation
]
