name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## What's Changed

            - Enhanced AI analysis with 5 additional modules
            - Corporate data exposure detection
            - Automated vulnerability discovery
            - Threat intelligence correlation
            - Enhanced binary reconstruction
            - Security demonstration generation

            ## Installation

            ```bash
            pip install reveng-toolkit
            ```

            ## Docker

            ```bash
            docker pull reveng/cli:${{ github.ref_name }}
            docker pull reveng/web:${{ github.ref_name }}
            ```

            ## Full Changelog

            See [CHANGELOG.md](CHANGELOG.md) for full details.

  build-python-package:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Upload Python package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: dist/
          asset_name: python-package
          asset_content_type: application/zip

  build-docker-images:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t reveng/cli:${{ github.ref_name }} .
          docker build -t reveng/web:${{ github.ref_name }} -f web_interface/Dockerfile.frontend ./web_interface
          docker build -t reveng/backend:${{ github.ref_name }} -f web_interface/Dockerfile.backend ./web_interface
          docker build -t reveng/ai-service:${{ github.ref_name }} -f web_interface/Dockerfile.ai-service ./web_interface
          docker build -t reveng/worker:${{ github.ref_name }} -f web_interface/Dockerfile.worker ./web_interface

          docker push reveng/cli:${{ github.ref_name }}
          docker push reveng/web:${{ github.ref_name }}
          docker push reveng/backend:${{ github.ref_name }}
          docker push reveng/ai-service:${{ github.ref_name }}
          docker push reveng/worker:${{ github.ref_name }}

          # Tag as latest
          docker tag reveng/cli:${{ github.ref_name }} reveng/cli:latest
          docker tag reveng/web:${{ github.ref_name }} reveng/web:latest
          docker tag reveng/backend:${{ github.ref_name }} reveng/backend:latest
          docker tag reveng/ai-service:${{ github.ref_name }} reveng/ai-service:latest
          docker tag reveng/worker:${{ github.ref_name }} reveng/worker:latest

          docker push reveng/cli:latest
          docker push reveng/web:latest
          docker push reveng/backend:latest
          docker push reveng/ai-service:latest
          docker push reveng/worker:latest

  publish-pypi:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  notify-release:
    runs-on: ubuntu-latest
    needs: [create-release, build-python-package, build-docker-images, publish-pypi]
    steps:
      - name: Notify release
        run: |
          echo "Release ${{ github.ref }} has been published!"
          echo "PyPI: https://pypi.org/project/reveng-toolkit/"
          echo "Docker Hub: https://hub.docker.com/r/reveng/cli"
          echo "GitHub Release: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
